### PR TITLE
Clear start delay when start is selected

### PR DESCRIPTION
**Pull request by AllanMar**
This is a cheap fix, ideally the delay would always be saved but ignored if only "Start" is selected.

### CODE REVIEW

**Comment by ericyanush** [comment]
When exactly does this come into play? If "Delay Start" is selected, then the user is prompted to setup a delay timer before the recipe sequence begins, however when the user selects "Start" there is never an option to setup a delay timer, so there shouldn't be one to clear. Are we accidentally setting up an arbitrary delay timer when there shouldn't be?

**Comment by AllanMar** [comment]
When a user selects Start a delay is not asked for and BT proceeds to Fill step. However when you continue from the fill step the BT checks if there is a delay saved. If the user has previously started another brew with delay this is still saved and so the previous delay is applied.

I suppose another option would be to clear delay upon completion of program, although slightly more complex.

**Comment by ericyanush** [comment]
I think that the more appropriate fix would be then to have the saved delay removed when the program has ended and is no longer relevant.

**Comment by AllanMar** [comment]
Have to account for the possibility of two programs running scenario in that case. (Starting a 2nd program before the 1st completes)

I suppose another option would be to clear it upon completion of the delay step. The more appropriate fix I believe would be to ignore it if start was selected, that way the delay would be saved if you planned to use it again sometime.

This way remains the simplest IMHO, and fits best within the current setup.

**Comment by ericyanush** [comment]
Clearing it at the completion of the delay step would also be appropriate, seeing as how we cannot have a second program start when the mash zone is in use, but I definitely believe it should not be the responsibility of a newly starting program to clean up after the last program that has run.

**Comment by AllanMar** [comment]
Changed to clear on step exit/completion. Not yet tested, although should be pretty straight forward.

**Comment by AllanMar** [comment]
Just noticed this isn't going to work due to a previous commit.
7158f9b21c2eb67f7d8e9c6471211a24907b97df
I agree I don't know why the != -1 was there, but you can't use !=0 as you'll never be able to clear the delay mins (via UI or otherwise)

**Comment by ericyanush** [comment]
Good catch! The if comparison is redundant, and does't need to be there at all.

**Pull request closed without merging**
